# Generated by Django 3.0.3 on 2020-02-27 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Language',
            new_name='language',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Mobile',
            new_name='mobile',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Region',
            new_name='region',
        ),
    ]
